### ISSUE TITLE
Problem Running node authorize.js

### ISSUE THREAD

**Issue by raspberrypi9** [randomBrainstormer/MMM-GoogleCalendar#76]
I generated an Oauth client ID in the Google interface and placed it in the file credentials.json in the MMM-GoogleCalendar directory.  When I run: node authorize.js, it says:

MMM-GoogleCalendar: Error loading credentials Error: ENOENT: no such file or directory, open '/home/mjw/MagicMirror/modules/MMM-GoogleCalendar/token.json'

I tried cp credentials.json token.json but I got:

MMM-GoogleCalendar: Error loading credentials Error: The incoming JSON object does not contain a client_email field

I'm not sure what else to try now.  If you would please offer some help, I would really appreciate it.  Thank you.

**Comment by sdetweil** [comment]
can you edit the credentials.json 

it is missing a field
 The incoming JSON object does not contain a client_email field

did you provide all the info, and select the right type of credentials?

**Comment by raspberrypi9** [comment]
I did download the credentials but it doesn't have a client_email field.  Should it?
I tried hand editing it to add one but that didn't work 
I am doing  OAuth client ID
Also, I put the credentials file as credentials.json in the MMM-Google Calendar dir but it was looking for a token.js

**Comment by Sebastardito** [comment]
Here the same, these are my outputs:

node@mm:/opt/magic_mirror/modules/MMM-GoogleCalendar$ node authorize.js
(node:193) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
MMM-GoogleCalendar: Error loading credentials Error: ENOENT: no such file or directory, open '/opt/magic_mirror/modules/MMM-GoogleCalendar/token.json'
    at async open (node:internal/fs/promises:638:25)
    at async Object.readFile (node:internal/fs/promises:1238:14)
    at async loadSavedCredentialsIfExist (/opt/magic_mirror/modules/MMM-GoogleCalendar/authorize.js:22:21)
    at async authorize (/opt/magic_mirror/modules/MMM-GoogleCalendar/authorize.js:55:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/opt/magic_mirror/modules/MMM-GoogleCalendar/token.json'
}

And after "cp credentials.json token.json":

node@mm:/opt/magic_mirror/modules/MMM-GoogleCalendar$ node --trace-deprecation authorize.js
(node:346) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:399:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:338:10)
    at loadBuiltinModule (node:internal/modules/helpers:114:7)
    at Function._load (node:internal/modules/cjs/loader:1100:17)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (/opt/magic_mirror/modules/MMM-GoogleCalendar/node_modules/whatwg-url/lib/url-state-machine.js:2:18)
MMM-GoogleCalendar: Error loading credentials Error: The incoming JSON object does not contain a client_email field
    at JWT.fromJSON (/opt/magic_mirror/modules/MMM-GoogleCalendar/node_modules/google-auth-library/build/src/auth/jwtclient.js:210:19)
    at AuthPlus.fromJSON (/opt/magic_mirror/modules/MMM-GoogleCalendar/node_modules/google-auth-library/build/src/auth/googleauth.js:385:20)
    at loadSavedCredentialsIfExist (/opt/magic_mirror/modules/MMM-GoogleCalendar/authorize.js:24:24)
    at async authorize (/opt/magic_mirror/modules/MMM-GoogleCalendar/authorize.js:55:16)

**Comment by nmlynch94** [comment]
The no such file or directory error log is a red herring due to poor error handling. 

What is likely happening is that the local-auth library is trying to open your default browser unsuccessfully which is what happened to me. As a band-aid fix, I edited `node_modules/@google-cloud/local-auth/build/src/index.js` and added `console.log("URL: " + authorizeUrl)` after this block of code:
```
            // open the browser to the authorize url to start the workflow
            const authorizeUrl = client.generateAuthUrl({
                redirect_uri: redirectUri.toString(),
                access_type: 'offline',
                scope: scopes.join(' '),
            });
```

and then you can copy the link that prints in the console next time you run it.

**Comment by aa0pb** [comment]
Howdy, I am running in to the same issue.  I followed the instructions, but on here it says select internal and I did not have that option and selected external with all the same settings.  I downloaded the credentials.json and when I run the authorize.js it errors out with what is below.  This is a new install as of 2 days ago.

> (node:70729) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> (Use `node --trace-deprecation ...` to show where the warning was created)
> MMM-GoogleCalendar: Error loading credentials Error: ENOENT: no such file or directory, open '/home/phil/MagicMirror/modules/MMM-GoogleCalendar/token.json'
>     at async open (node:internal/fs/promises:639:25)
>     at async Object.readFile (node:internal/fs/promises:1243:14)
>     at async loadSavedCredentialsIfExist (/home/phil/MagicMirror/modules/MMM-GoogleCalendar/authorize.js:23:21)
>     at async authorize (/home/phil/MagicMirror/modules/MMM-GoogleCalendar/authorize.js:56:16) {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: '/home/phil/MagicMirror/modules/MMM-GoogleCalendar/token.json'
> }

Then I have to cancel out, it just sits there.

Any help would be appreciated.

**Comment by pseudosystem** [comment]
> The no such file or directory error log is a red herring due to poor error handling.
> 
> What is likely happening is that the local-auth library is trying to open your default browser unsuccessfully which is what happened to me. As a band-aid fix, I edited `node_modules/@google-cloud/local-auth/build/src/index.js` and added `console.log("URL: " + authorizeUrl)` after this block of code:
> 
> ```
>             // open the browser to the authorize url to start the workflow
>             const authorizeUrl = client.generateAuthUrl({
>                 redirect_uri: redirectUri.toString(),
>                 access_type: 'offline',
>                 scope: scopes.join(' '),
>             });
> ```
> 
> and then you can copy the link that prints in the console next time you run it.

This was a successful solution for me. Thank you!

**Comment by pseudosystem** [comment]
> Howdy, I am running in to the same issue. I followed the instructions, but on here it says select internal and I did not have that option and selected external with all the same settings. I downloaded the credentials.json and when I run the authorize.js it errors out with what is below. This is a new install as of 2 days ago.
> 
> > (node:70729) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> > (Use `node --trace-deprecation ...` to show where the warning was created)
> > MMM-GoogleCalendar: Error loading credentials Error: ENOENT: no such file or directory, open '/home/phil/MagicMirror/modules/MMM-GoogleCalendar/token.json'
> > at async open (node:internal/fs/promises:639:25)
> > at async Object.readFile (node:internal/fs/promises:1243:14)
> > at async loadSavedCredentialsIfExist (/home/phil/MagicMirror/modules/MMM-GoogleCalendar/authorize.js:23:21)
> > at async authorize (/home/phil/MagicMirror/modules/MMM-GoogleCalendar/authorize.js:56:16) {
> > errno: -2,
> > code: 'ENOENT',
> > syscall: 'open',
> > path: '/home/phil/MagicMirror/modules/MMM-GoogleCalendar/token.json'
> > }
> 
> Then I have to cancel out, it just sits there.
> 
> Any help would be appreciated.

See the solution by nmlynch94 above

**Comment by ludalito** [comment]
Hello,

Same problem here, but I don't have `node_modules/@google-cloud` to apply nmlynch94's solution.
I ran
`npm install`
that says
`up to date, audited 383 packages in 2s`

`65 packages are looking for funding`
`  run npm fund for details`

`1 low severity vulnerability`

`To address all issues, run:`
`  npm audit fix`

`Run npm audit for details.`

I have to say that I have no skill in js.

Thanks for your help

**Comment by utdrmac** [comment]
Same situation as everyone else. I'm attempting to set this up via SSH and thus the authorize.js cannot open a browser. The documentation clearly states "The script will output a URL. Copy this URL." but no URL was ever output. Perhaps the google library has changed and the docs are now out of date?

In any case, @nmlynch94 's fix worked for me. It output the URL, I copied into browser, auth'd, then it tried to redirect me to 'http://localhost:42247/...' To finish, I opened a second SSH session and simply `curl`'d that URL which finally completed the entire process.

Please update the docs, or provide a fix so that the URL is output as indicated in the docs.

**Comment by kash1982** [comment]
im not the best when i comes to programming so ive done the fix but i get the following after the op error.

node authorize.js
/home/pi/MagicMirror/modules/MMM-GoogleCalendar/node_modules/@google-cloud/local-auth/build/src/index.js:124
    });
     ^

SyntaxError: Unexpected token ')'
    at wrapSafe (node:internal/modules/cjs/loader:1620:18)
    at Module._compile (node:internal/modules/cjs/loader:1662:20)
    at Object..js (node:internal/modules/cjs/loader:1820:10)
    at Module.load (node:internal/modules/cjs/loader:1423:32)
    at Function._load (node:internal/modules/cjs/loader:1246:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1445:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-GoogleCalendar/authorize.js:4:26)

**Comment by unskilleddrahim** [comment]
hey there, i am pretty much stuck at point "3. Provide Authorization Code to Script". I have the full URL pasted and confirmed with enter, after the authorize.js gave me the URL for login, but nothing happens.

URL: http://localhost:45761/?code=**CODEHERE**&scope=https://www.googleapis.com/auth/calendar.readonly 

I've also tried to curl the url via a second terminal session like @utdrmac stated, but it says it's unable to connect to localhost on port 45761


Anyone able to help me out, pls?

**Comment by jamindaw** [comment]
I am trying to get it working on my raspberry pi via SSH and I came to the same issue. I managed to get it to work but creating the token.json another computer (using the script below) and copying the file across.

`
    import os
    from google.auth.transport.requests import Request
    from google.oauth2.credentials import Credentials
    from google_auth_oauthlib.flow import InstalledAppFlow

    SCOPES = ['https://www.googleapis.com/auth/calendar']

    def generate_token():
        creds = None

        if os.path.exists('token.json'):
            creds = Credentials.from_authorized_user_file('token.json', SCOPES)
    
        if not creds or not creds.valid:
            if creds and creds.expired and creds.refresh_token:
                creds.refresh(Request())
            else:
                flow = InstalledAppFlow.from_client_secrets_file(
                    'credentials.json', SCOPES)
                creds = flow.run_local_server(port=0)
            
            with open('token.json', 'w') as token:
                token.write(creds.to_json())
                print("Successfully created token.json")

    if __name__ == '__main__':
        generate_token()
`

**Comment by bembudo** [comment]
late response here, but there is no need to create a token.json file. you need to replace  the async function authorize() with the below found in  authorize.js. this code is more explicit so it always prints the URL when no token exists.

`async function authorize() {
  let client = await loadSavedCredentialsIfExist();
  if (client) return client;

  console.log("MMM-GoogleCalendar: No token found, starting OAuth flow...");

  // Headless / manual OAuth flow
  const { OAuth2 } = google.auth;
  const credentials = JSON.parse(await fs.readFile(CREDENTIALS_PATH));
  const { client_id, client_secret, redirect_uris } = credentials.installed;
  const oAuth2Client = new OAuth2(client_id, client_secret, redirect_uris[0]);

  const authUrl = oAuth2Client.generateAuthUrl({
    access_type: "offline",
    scope: SCOPES
  });

  console.log("Authorize this app by visiting this url:\n", authUrl);

  const readline = require("readline").createInterface({
    input: process.stdin,
    output: process.stdout
  });

  const code = await new Promise(resolve => {
    readline.question("Enter the code from that page here: ", resolve);
  });
  readline.close();

  const { tokens } = await oAuth2Client.getToken(code);
  oAuth2Client.setCredentials(tokens);
  await saveCredentials(oAuth2Client);
  console.log("MMM-GoogleCalendar: token.json created successfully!");
  return oAuth2Client;
}
`

**Comment by jameskyawtx** [comment]
Were you able to resolve? I'm getting this error.

:~/MagicMirror/modules/MMM-GoogleCalendar $ node authorize.js
MMM-GoogleCalendar: Error loading credentials Error: ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/MMM-GoogleCalendar/token.json'
    at async open (node:internal/fs/promises:641:25)
    at async Object.readFile (node:internal/fs/promises:1245:14)
    at async loadSavedCredentialsIfExist (/home/pi/MagicMirror/modules/MMM-GoogleCalendar/authorize.js:22:21)
    at async authorize (/home/pi/MagicMirror/modules/MMM-GoogleCalendar/authorize.js:55:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/pi/MagicMirror/modules/MMM-GoogleCalendar/token.json'
}
MMM-GoogleCalendar: No token found, starting OAuth flow...
TypeError: Cannot read properties of undefined (reading '0')
    at authorize (/home/pi/MagicMirror/modules/MMM-GoogleCalendar/authorize.js:64:72)

**Comment by PerryRT** [comment]
FWIW, I had this same issue. It was resolved by doing two things - 

- finally closing out of the OAuth dialog box on the Google Cloud API page. I suspect/don't know that Google may not actually create the OAuth until you do that! (D'oh!)
- (and more importantly) the modified code posted by bembudo on [Feb 16th of this year](https://github.com/randomBrainstormer/MMM-GoogleCalendar/issues/76#issuecomment-3910843365) worked fine for me, except for one thing. It did not work for me when I copied the WHOLE url back into the script prompt as per the main instructions. What I had to do was to extract the code *from* the URL (that should be everything between "...code=" and ending in the character before the next "&"). This made everything work fine.

Hope that helps - Thanks!

**Comment by randomBrainstormer** [comment]
The `Error loading credentials ENOENT ... token.json` part is a red herring — authorize.js printed that on every normal first run and then carried on. The real problem was the next step, where it tried to open a browser on the machine running it and just hung if there wasn't one.

#104 fixes that (it prints the URL and you paste the redirect URL back), and drops the misleading message. The punycode deprecation warning was coming from a dependency that's now gone too.

@raspberrypi9 separately, on your question: no, credentials.json shouldn't have a client_email field. That field belongs to service account keys, which are a different credential type this module doesn't use. What you want is an OAuth client ID of type "Desktop app" — that file has an `installed` section with client_id and client_secret in it. The README is clearer about this now.

To try the branch:

```
cd ~/MagicMirror/modules/MMM-GoogleCalendar
git fetch origin fix/headless-authorize && git checkout fix/headless-authorize
npm install
rm -f token.json && node authorize.js
```
